# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Linbug
tagline:          'A blog about data science'
description:      'A blog about transitioning from life science to data science'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Lin Taylor'
  url:            http://linbug.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
