# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: 

# Setup
title:            Jose
tagline:          'A blog about data science'
description:      'A blog about transitioning from life science to data science'
url:              http://linbug.github.io/
baseurl:          http://linbug.github.io/

author:
  name:           'Jose Alex'
  url:            http://linbug.github.io/

paginate:         5

# Custom vars
          
avatar:           https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
github:           linbug


theme: jekyll-theme-cayman
